name: quiz_vetor
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  auto_size_text: ^2.1.0
  http: ^0.12.0+4
  share: ^0.6.3+6
  flutter_launcher_icons: ^0.7.4
  photo_view: ^0.10.3
  scoped_model: ^1.1.0
  toast: ^0.1.5

flutter_icons:
  image_path_android: "assets/android_icon.png"
  image_path_ios: "assets/android_icon.png"
  android: true
  ios: true
  adaptive_icon_background: "assets/android_bkg.png"
  adaptive_icon_foreground: "assets/android_icon.png"



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/logoVetor.png


  uses-material-design: true


